location:
  lat: 22.54691
  lon: 114.56853
  name: "大鹏半岛·杨梅坑"

scoring:
  low_cloud: [0, 30, 50]        # 0~30% =2分；30~50% =1分；其它=0分
  mid_high_cloud: [20, 60, 80]
  cloud_base_m: [500, 1000]
  visibility_km: [5, 10]
  wind_ms: [1, 2, 5, 8]         # <1 或 >8 =0分；1~2 or 5~8 =1分；2~5 =2分
  dewpoint_diff: [1, 3]
  precip_mm: [0.1, 1.0]         # <0.1mm=2分；0.1~1mm=1分；>=1mm=0分

# 低云墙模型参数（多点采样，而非卫星）
coast_normal_deg: 90          # 岸线法向角度（度），用于“上/离岸风”判断
cloudbase_coef_m_per_C: 125   # 云底估算系数 m/℃（可后续用历史校准更新）
sector_offsets_deg: [-20, -10, 0, 10, 20]
sector_dists_km: [20, 40, 60]

cloudwall:
  sample_km: [20, 50, 80, 120]  # 从站点沿日出/日落方向取的采样距离
  sunrise_azimuth: 90           # 日出方向（大致东方），可按季节再微调
  sunset_azimuth: 270           # 日落方向（大致西方）

# 云底估算系数自动校准参数
cloudbase_estimate:
  default_coef_m_per_deg: 125   # 初始：每 1℃ 露点差≈125 m 云底抬升
  min_samples: 10               # 至少多少条有真实云底的历史样本才启动校准
  max_window_days: 45           # 回看多少天数据做校准
  clip_min: 60                  # 系数下限（避免极端值）
  clip_max: 200                 # 系数上限

paths:
  log_scores: "logs/scores_%Y-%m.csv"
  log_cloud:  "logs/cloud_%Y-%m.csv"
  log_calib:  "logs/calib_%Y-%m.csv"   # 新增：记录每次校准结果
scene_tweaks:
  sector_half_angle_deg: 35         # 扇区半角（看太阳方位 ±35°）
  sector_radii_km: [20, 50, 80, 120]# 用你的 samples 半径
  coast_azimuth_deg: 110            # 海岸线法向（面朝海的方向）；杨梅坑可先填 110
  horizon_elev_deg: 0.3             # 有效地平线仰角（小岛/海平面），先给 0.3° 经验值
  wind_ok_range_ms: [2.0, 8.0]      # 风速有利范围
  weights:                          # 天窗因子权重
    frag: 0.45                      # 碎片度权重
    sector: 0.35                    # 扇区低云的“低值/均值”权重
    wind: 0.20                      # 风向修正权重
  tianchuang_threshold: 0.55        # 天窗因子阈值（>阈值算“有缝”）
  occlusion_discount_range: [0.6, 0.85] # 有缝时对低云遮挡项打折的系数区间
