location:
  lat: 22.54691
  lon: 114.56853
  name: "大鹏半岛·杨梅坑"

scoring:
  low_cloud:      [0, 30, 50]
  mid_high_cloud: [20, 60, 80]
  cloud_base_m:   [500, 1000]
  visibility_km:  [5, 10]
  wind_ms:        [1, 2, 5, 8]
  dewpoint_diff:  [1, 3]

cloudwall:
  roi: [11800, 6200, 200, 150]   # 先随便用，跑几天再调
  gray_threshold: 110
  ratio_warn: 0.12
  frames: 6
  step_min: 10

paths:
  log_scores: "logs/scores_%Y-%m.csv"
  log_cloud:  "logs/cloudwall_%Y-%m.csv"
