location:
  lat: 22.54691
  lon: 114.56853
  name: "大鹏半岛·杨梅坑"

scoring:
  low_cloud:      [0, 30, 50]
  mid_high_cloud: [20, 60, 80]
  cloud_base_m:   [500, 1000]
  visibility_km:  [5, 10]
  wind_ms:        [1, 2, 5, 8]
  dewpoint_diff:  [1, 3]
  precip_mm:      [0.1, 1.0]    # <0.1mm=2分；0.1~1mm=1分；>=1mm=0分

cloudwall:
  roi: [11800, 6200, 200, 150]   # 先随便用，跑几天再调
  gray_threshold: 110
  ratio_warn: 0.12
  frames: 6
  step_min: 10

paths:
  log_scores: "logs/scores_%Y-%m.csv"
  log_cloud:  "logs/cloudwall_%Y-%m.csv"
  
cloudbase_estimate:
  default_coef_m_per_deg: 125        # 默认 125 m/℃（≈400 ft/℃）
  min_samples: 10                    # 至少多少条样本才触发自动校准
  max_window_days: 45                # 回溯多少天的数据做校准
  clip_min: 60                       # 系数下限，避免异常值（单位 m/℃）
  clip_max: 200                      # 系数上限

paths:
  log_scores: "logs/scores_%Y-%m.csv"
  log_cloud:  "logs/cloud_%Y-%m.csv"
  log_calib:  "logs/calib_%Y-%m.csv"   # 新增：记录每次校准结果
