name: Sunset Forecast

on:
  schedule:
    # 每天北京时间 05:30 运行（UTC 21:30 前一天）
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  run-sunset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run sunset forecast
        run: python sunset_bot.py

      # —— 选最新的日落报告（无文件也不报错） ——
      - name: Pick latest report
        id: pick
        shell: bash
        run: |
          set +e
          shopt -s nullglob
          latest=""
          files=(out/sunset_*.txt)
          if (( ${#files[@]} )); then
            latest=$(ls -t out/sunset_*.txt | head -n 1)
            echo "latest=$latest" >> "$GITHUB_OUTPUT"
            echo "base=$(basename "$latest")" >> "$GITHUB_OUTPUT"
          fi
          YM=$(date +'%Y-%m')
          [ -f "logs/scores_${YM}.csv" ] && echo "scores=logs/scores_${YM}.csv" >> "$GITHUB_OUTPUT"
          [ -f "logs/cloud_${YM}.csv"  ] && echo "cloud=logs/cloud_${YM}.csv"  >> "$GITHUB_OUTPUT"
          [ -f "logs/calib_${YM}.csv"  ] && echo "calib=logs/calib_${YM}.csv"  >> "$GITHUB_OUTPUT"
          echo "Picked latest=$latest" ; ls -al out || true ; ls -al logs || true

      # —— 把正文转成 HTML（转义+换行 <br/>） ——
      - name: Prepare email body (HTML)
        id: body
        if: ${{ steps.pick.outputs.latest != '' }}
        shell: bash
        run: |
          set -e
          FILE="${{ steps.pick.outputs.latest }}"
          HTML=$(python - <<'PY' "$FILE"
import sys, html
txt = open(sys.argv[1], 'r', encoding='utf-8').read()
print(html.escape(txt).replace('\n','<br/>'))
PY
)
          echo "html=${HTML}" >> "$GITHUB_OUTPUT"

      - name: Send email (sunset)
        if: ${{ steps.pick.outputs.latest != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          secure: true
          username: ${{ secrets.QQ_SMTP_USER }}
          password: ${{ secrets.QQ_SMTP_PASS }}
          to: 248882568@qq.com
          from: Sunrise Auto <${{ secrets.QQ_SMTP_USER }}>
          subject: "日落预报 - ${{ steps.pick.outputs.base }}"
          content_type: text/html
          body: ${{ steps.body.outputs.html }}
          attachments: |
            ${{ steps.pick.outputs.latest }}
            ${{ steps.pick.outputs.scores }}
            ${{ steps.pick.outputs.cloud }}
            ${{ steps.pick.outputs.calib }}

      # 失败兜底
      - name: Send failure email
        if: failure() || ${{ steps.pick.outputs.latest == '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          secure: true
          username: ${{ secrets.QQ_SMTP_USER }}
          password: ${{ secrets.QQ_SMTP_PASS }}
          to: 248882568@qq.com
          from: Sunrise Auto <${{ secrets.QQ_SMTP_USER }}>
          subject: "【告警】日落预报任务失败 - ${{ github.repository }}"
          body: |
            任务失败或未产生日落报告。
            仓库: ${{ github.repository }}
            分支: ${{ github.ref_name }}
            运行: ${{ github.run_id }}
            请在 Actions 查看日志。
